[project]
authors = ["?"]
entry = "main.sw"
license = "MIT"
name = "arcana-vault"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.7.0" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.25.0" }
